### ISSUE TITLE
MAX called with invalid number of arguments

### ISSUE THREAD

**Issue by stugol** [usocket/usocket#19] opened 2016-05-07 23:53 UTC
I'm using `(usocket:wait-for-input client-socket :timeout 0.1 :ready-only t)` in a loop inside a thread, and getting the following error:

```
MAX called with invalid number of arguments: 0
```

I don't know why this happens, or under what circumstances; I just know that it _does_. Maybe there's a race condition? Maybe the socket is being closed? Either way, some kind of "invalid socket" error should be raised, rather than crashing.

**Comment by phoe-krk** [comment] 2016-05-14 07:11
@stugol When there's a Lisp error, an implementation prints a stack trace that shows a list of all functions called up to this point. Could you paste/post it here?

**Comment by stugol** [comment] 2016-05-14 16:42
Nope, because in the seven days since I raised this issue, I have modified my code and it no longer does it.

**Comment by binghe** [comment] 2016-05-16 07:41
Hi stugol, what's your Lisp implementation and version with this issue?

**Comment by phoe-krk** [comment] 2016-05-16 08:55
@stugol I'm glad your issue is over thanks to a workaround, but if you found a bug, it would be nice if you stopped for a while and took enough information for other people to be able to reproduce and fix it in the future.

**Comment by stugol** [comment] 2016-05-17 13:44
I'm using "SBCL 1.2.4.debian".

I wasn't prepared to halt development for the 7 days it took to get a response. If it happens again, I will take a snapshot of the source at that point.

I've tried modifying the code again to reproduce the problem, but have thus far been unsuccessful.

**Comment by binghe** [comment] 2016-05-17 14:31
Well, based on the platform, I think the only possibility to get the same error message is this one: (usocket:wait-for-input nil), if we assume you only call exported API functions:

* (usocket:wait-for-input nil)

debugger invoked on a SB-INT:SIMPLE-PROGRAM-ERROR in thread
#<THREAD "main thread" RUNNING {1002FEE853}>:
  invalid number of arguments: 0

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(MAX) [tl,external]

CMUCL also report the same error, while ABCL and LispWorks run into infinite waiting and never returns unless there's TIMEOUT. (this actually make sense: waiting for nothing should never return).

Of course, people won't call (usocket:wait-for-input nil) directly, but if the waiting socket list is a variable in their application, it's quite possible that due to some reasons the variable becomes NIL.

I'm going to submit a patch to let WAIT-FOR-INPUT return NIL "immediately" in all platforms, no matter what value of TIMEOUT is) in this special case. Make sense?

**Comment by stugol** [comment] 2016-05-17 14:39
Pretty sure I wasn't calling it with nil.

**Comment by binghe** [comment] 2018-09-25 19:36
Hi,

finally another user met the same issue and provided a backtrace. And now it’s clear that usocket’s `WAIT-FOR-INPUT-INTERNAL` is not thread-safe (in SBCL/Linux). I’ll close this issue and use #38 for tracking the progress, where I worked out a patch.

—binghe

**Closed by binghe** 2018-09-25 19:36 UTC
