### ISSUE TITLE
Should NS-TRY-AGAIN-CONDITION be a SERIOUS-CONDITION?

### ISSUE THREAD

**Issue by frodef** [usocket/usocket#79] opened 2022-01-06 18:40 UTC
I just got thrown into the debugger with a USOCKET:NS-TRY-AGAIN-CONDITION signalled.

This surprised me, because the code was wrapped in a HANDLER-BIND dealing with SERIOUS-CONDITION. The CLHS entry for SERIOUS-CONDITION states: All conditions serious enough to require interactive intervention if not handled should inherit from the type serious-condition.

Because Usocket sent me to the debugger, I suppose the condition is such that this really should be a SERIOUS-CONDITION, yes?

**Comment by binghe** [comment] 2022-01-07 06:43
Well, it's serious enough if your code tries to resolve a hostname into IP addresses but failed, when the rest of your code can only proceed with the IP addresses.   This is why a warning is not enough.   Better to use a condition handler to catch the condition and do something in your code, or use `IGNORE-ERRORS` to get `NIL` instead.

**Comment by frodef** [comment] 2022-01-07 11:32
If I understand all this correctly, IGNORE-ERRORS handles only ERRORs, a subclass of SERIOUS-CONDITIONS, and therefore won't handle the NS-CONDITION. In other words, I did try to use (something equivalent to) IGNORE-ERRORS, and that doesn't work, for the reason stated.

**Comment by frodef** [comment] 2022-01-07 12:45
...so to elaborate, I suspect that this condition should really be an ERROR, not just a SERIOUS-CONDITION.

Actually the concept of a TRY-AGAIN-CONDITION seems strange to me, because the condition should describe the "exceptional situation" as such, not how one might go about dealing with it (which is more the realm of restarts).

**Comment by binghe** [comment] 2022-01-07 23:41
> I just got thrown into the debugger with a USOCKET:NS-TRY-AGAIN-CONDITION signalled.
> 
> This surprised me, because the code was wrapped in a HANDLER-BIND dealing with SERIOUS-CONDITION. The CLHS entry for SERIOUS-CONDITION states: All conditions serious enough to require interactive intervention if not handled should inherit from the type serious-condition.
> 
> Because Usocket sent me to the debugger, I suppose the condition is such that this really should be a SERIOUS-CONDITION, yes?

I checked the code (`condition.lisp`). It seems that `NS-TRY-AGAIN-CONDITION` inherits from `CONDITION` (not `serious-condition`).  The condition is put into the list `+unix-ns-error-map+` and eventually trigger by an explicitly call of `SIGNAL` from each backends - perhaps this is why your `HANDLER-BIND` catched it.   I don't think the behavior may change if `NS-TRY-AGAIN-CONDITION` inherits from `ERROR` instead.

**Comment by frodef** [comment] 2022-01-08 00:42
The fact that NS-TRY-AGAIN-CONDITION inherits from CONDITION (not SERIOUS-CONDITION or perhaps better from ERROR( is precisely what I am suggesting should change.

The condition must have been signalled by way of ERROR or something equivalent (certainly not SIGNAL), since I ended up in the debugger. Again, to have a condition that is not an ERROR signalled by the function ERROR, seems to me a bug that should be fixed.

My HANDLER-BIND did NOT catch the condition, nor would IGNORE-ERRORS, contrary to your own expectation. It seems clear to me that this would in fact change (for the better and to expectations) if NS-TRY-AGAIN-CONDITION was to inherit from ERROR.

**Comment by binghe** [comment] 2022-01-08 18:04
> The condition must have been signalled by way of ERROR or something equivalent (certainly not SIGNAL), since I ended up in the debugger. Again, to have a condition that is not an ERROR signalled by the function ERROR, seems to me a bug that should be fixed.

Which Lisp platform are you using? If `NS-TRY-AGAIN-CONDITION` is not signalled by `SIGNAL`, this is the actual bug and should be fixed in the corresponding backend code.  Will this solution work for you?

For instance, if you take a look at the function `HANDLE-CONDITION` in `backend/sbcl.lisp`, it first check if the condition is `serious-condition` (parent condition of `error`) or `condition`, then use `ERROR` for the former case, `SIGNAL` for the latter.  However, currently this business logic is repeated in the code for each backend.

**Comment by frodef** [comment] 2022-01-08 18:14
Thanks, now your answers make more sense to me. This is indeed sbcl on linux. I'll see if I can reproduce the issue and inspect more closely how the debugger is triggered.

**Comment by death** [comment] 2022-03-10 21:03
> For instance, if you take a look at the function `HANDLE-CONDITION` in `backend/sbcl.lisp`, it first check if the condition is `serious-condition` (parent condition of `error`) or `condition`, then use `ERROR` for the former case, `SIGNAL` for the latter. However, currently this business logic is repeated in the code for each backend.

The implementation-specific condition type `sb-bsd-sockets:try-again-error` is indeed a subtype of `error` (and hence `serious-condition`), but then usocket calls `error` with symbol `usocket:ns-try-again-condition` passed as the datum. This symbol names a condition type that is not a subtype of `error`.

P.S. The way I stumbled on this issue (or a related one) is by having a worker thread "stuck" for a few days until I interrupted it because, while a timeout is passed to `usocket:socket-connect`, the latter calls `usocket:get-hosts-by-name` with no notion of any timeout.

**Comment by binghe** [comment] 2022-03-11 07:26
> The implementation-specific condition type `sb-bsd-sockets:try-again-error` is indeed a subtype of `error` (and hence `serious-condition`), but then usocket calls `error` with symbol `usocket:ns-try-again-condition` passed as the datum. This symbol names a condition type that is not a subtype of `error`.
> 
> P.S. The way I stumbled on this issue (or a related one) is by having a worker thread "stuck" for a few days until I interrupted it because, while a timeout is passed to `usocket:socket-connect`, the latter calls `usocket:get-hosts-by-name` with no notion of any timeout.

Thanks for the analysis. So what's your suggestion? Should we change the parent class of `usocket:ns-try-again-condition` to `serious-condition` to match SBCL (and possibly resolve all related issues here)?

**Comment by death** [comment] 2022-03-11 09:22
Since it's a situation that has to be dealt with by the user, I would lean towards making it into an error, like SBCL does.

**Comment by binghe** [comment] 2022-03-11 19:03
> Since it's a situation that has to be dealt with by the user, I would lean towards making it into an error, like SBCL does.

Now I have defined another `ns-try-again-error` condition (inherited from `error`) and used it instead.

I will do some tests during this weekend, and if there's no new regressions I'll make a new release (it's been more than two years since the previous one).

**Comment by death** [comment] 2022-03-12 12:16
Looks good to me (on SBCL), thanks!

**Comment by binghe** [comment] 2022-03-13 20:14
Consider this issue closed. Usocket 0.8.4 has been released.

**Closed by binghe** 2022-03-13 20:14 UTC
